            <!-- Fixed navbar -->
            <div class="navbar navbar-default navbar-fixed-top">
               <div class="container">
                  <div class="navbar-header">
                     <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                     <span class="icon-bar"></span>
                     <span class="icon-bar"></span>
                     <span class="icon-bar"></span>
                     </button>
                     <a class="navbar-brand" href="/"><img src="img/logo.png" alt="mastercoin"></a>
                  </div>
                  <div class="navbar-collapse collapse">
                     <ul class="nav navbar-nav navbar-right">
                        <li class="c-visible-xs"><a href="wallet.html">Wallet</a></li>
                        <li><a href="/">Recent</a></li>
                        <li><a href="/">Orderbook</a></li>
                        <li><a href="About.html">Info</a></li>
                        <li>
                           <a class="searchLI">
                              <div class="search">
                                 <select class="select optional combobox customDropdown"
                                    id="searchText" name="searchText">
                                 </select>
                              </div>
                           </a>
                        </li>
                     </ul>
                  </div>
               </div>
            </div>
