      </title>
      <noscript>
         Java Script has been disabled!
         <meta http-equiv="refresh" content="0;url=javascript_required.html">
      </noscript>
      <!-- Bootstrap core CSS -->
      <link href="bower_components/bootstrap/dist/css/bootstrap.css" rel="stylesheet">
      <link href="css/bootstrap-theme.css" rel="stylesheet">
      <link href="css/search.css" rel="stylesheet" />
      <script src="bower_components/jquery/jquery.min.js"></script>
      <script src="bower_components/angular/angular.min.js"></script>
      <script src="btcutils.js"></script>
      <script src="js/truncate.js"></script>
      <script src="masterPage.js"></script>
      <script src="btc02.js"></script>
      <script src="js/bootstrap-combobox.js"></script>
      <script>
         var myApp = angular.module('myApp', ['truncate']);
      </script>
      <script src="bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
